[package]
name = "rust-micro-service-demo"
version = "0.1.0"
authors = ["Aaron Qian <aq1018@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
