[package]
name = "fgo-import"
version = "0.1.0"
authors = ["Aaron Qian <aq1018@gmail.com>"]
edition = "2018"

[dependencies]
postgres = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "2.33"

[profile.release]
lto = true